export const SIGNUP_START   = 'SIGNUP_START'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILED  = 'SIGNUP_FAILED'

export const LOGIN_START    = 'LOGIN_START'
export const LOGIN_SUCCESS  = 'LOGIN_SUCCESS'
export const LOGIN_FAILED   = 'LOGIN_FAILED'

export const LOGOUT_START   = 'LOGOUT_START'
export const LOGOUT_SUCCESS	= 'LOGOUT_SUCCESS'

export const REAUTHENTICATE_START   = 'REAUTHENTICATE_START'
export const REAUTHENTICATE_SUCCESS = 'REAUTHENTICATE_SUCCESS'
export const REAUTHENTICATE_FAILED  = 'REAUTHENTICATE_FAILED'

export const UPDATE_PROFILE_START   = 'UPDATE_PROFILE_START'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED  = 'UPDATE_PROFILE_FAILED'

export const LOAD_CATEGORIES_START    = 'LOAD_CATEGORIES_START'
export const LOAD_CATEGORIES_SUCCESS  = 'LOAD_CATEGORIES_SUCCESS'
export const LOAD_CATEGORIES_FAILED   = 'LOAD_CATEGORIES_FAILED'

export const CREATE_EVENT_START   = 'CREATE_EVENT_START'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_FAILED  = 'CREATE_EVENT_FAILED'

export const UPDATE_EVENT_START   = 'UPDATE_EVENT_START'
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS'
export const UPDATE_EVENT_FAILED  = 'UPDATE_EVENT_FAILED'

export const FETCH_EVENTS_START   = 'FETCH_EVENTS_START'
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
export const FETCH_EVENTS_FAILED  = 'FETCH_EVENTS_FAILED'

export const SET_EVENTS_ACTIVE_FILTER     = 'SET_EVENTS_ACTIVE_FILTER'
export const SET_MY_EVENTS_ACTIVE_FILTER  = 'SET_MY_EVENTS_ACTIVE_FILTER'

export const APPLY_NEW_EVENTS     = 'APPLY_NEW_EVENTS'
export const APPLY_EVENT_CHANGES  = 'APPLY_EVENT_CHANGES'

export const SET_EVENT_DETAIL = 'SET_EVENT_DETAIL'
