export const SIGNUP_START   = 'SIGNUP_START'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILED  = 'SIGNUP_FAILED'

export const LOGIN_START    = 'LOGIN_START'
export const LOGIN_SUCCESS  = 'LOGIN_SUCCESS'
export const LOGIN_FAILED   = 'LOGIN_FAILED'

export const LOGOUT_START   = 'LOGOUT_START'
export const LOGOUT_SUCCESS	= 'LOGOUT_SUCCESS'

export const SEND_RESET_PASSWORD_EMAIL_START    = 'SEND_RESET_PASSWORD_EMAIL_START'
export const SEND_RESET_PASSWORD_EMAIL_SUCCESS  = 'SEND_RESET_PASSWORD_EMAIL_SUCCESS'
export const SEND_RESET_PASSWORD_EMAIL_FAILED   = 'SEND_RESET_PASSWORD_EMAIL_FAILED'

export const REAUTHENTICATE_START   = 'REAUTHENTICATE_START'
export const REAUTHENTICATE_SUCCESS = 'REAUTHENTICATE_SUCCESS'
export const REAUTHENTICATE_FAILED  = 'REAUTHENTICATE_FAILED'

export const UPDATE_PROFILE_START   = 'UPDATE_PROFILE_START'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED  = 'UPDATE_PROFILE_FAILED'

export const LOAD_CATEGORIES_START    = 'LOAD_CATEGORIES_START'
export const LOAD_CATEGORIES_SUCCESS  = 'LOAD_CATEGORIES_SUCCESS'
export const LOAD_CATEGORIES_FAILED   = 'LOAD_CATEGORIES_FAILED'

export const CREATE_EVENT_START   = 'CREATE_EVENT_START'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_FAILED  = 'CREATE_EVENT_FAILED'

export const UPDATE_EVENT_START   = 'UPDATE_EVENT_START'
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS'
export const UPDATE_EVENT_FAILED  = 'UPDATE_EVENT_FAILED'

export const FETCH_EVENTS_START   = 'FETCH_EVENTS_START'
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
export const FETCH_EVENTS_FAILED  = 'FETCH_EVENTS_FAILED'

export const SET_EVENTS_ACTIVE_FILTER     = 'SET_EVENTS_ACTIVE_FILTER'
export const SET_MY_EVENTS_ACTIVE_FILTER  = 'SET_MY_EVENTS_ACTIVE_FILTER'
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER'

export const APPLY_EVENT_CHANGES  = 'APPLY_EVENT_CHANGES'

export const SET_EVENT_DETAIL = 'SET_EVENT_DETAIL'

export const FETCH_USERS_START   = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILED  = 'FETCH_USERS_FAILED'

export const APPLY_USER_CHANGES  = 'APPLY_USER_CHANGES'
export const SET_USER_DETAIL     = 'SET_USER_DETAIL'

export const SET_USERS_ACTIVE_FILTER = 'SET_USERS_ACTIVE_FILTER'

export const ADD_FRIENDSHIP_START    = 'ADD_FRIENDSHIP_START'
export const ADD_FRIENDSHIP_SUCCESS  = 'ADD_FRIENDSHIP_SUCCESS'
export const ADD_FRIENDSHIP_FAILED   = 'ADD_FRIENDSHIP_FAILED'

export const CONFIRM_FRIENDSHIP_START   = 'CONFIRM_FRIENDSHIP_START'
export const CONFIRM_FRIENDSHIP_SUCCESS = 'CONFIRM_FRIENDSHIP_SUCCESS'
export const CONFIRM_FRIENDSHIP_FAILED  = 'CONFIRM_FRIENDSHIP_FAILED'

export const REJECT_FRIENDSHIP_START    = 'REJECT_FRIENDSHIP_START'
export const REJECT_FRIENDSHIP_SUCCESS  = 'REJECT_FRIENDSHIP_SUCCESS'
export const REJECT_FRIENDSHIP_FAILED   = 'REJECT_FRIENDSHIP_FAILED'

export const REMOVE_FRIENDSHIP_START    = 'REMOVE_FRIENDSHIP_START'
export const REMOVE_FRIENDSHIP_SUCCESS  = 'REMOVE_FRIENDSHIP_SUCCESS'
export const REMOVE_FRIENDSHIP_FAILED   = 'REMOVE_FRIENDSHIP_FAILED'

export const REQUEST_PARTECIPATION_START   = 'REQUEST_PARTECIPATION_START'
export const REQUEST_PARTECIPATION_SUCCESS = 'REQUEST_PARTECIPATION_SUCCESS'
export const REQUEST_PARTECIPATION_FAILED  = 'REQUEST_PARTECIPATION_FAILED'

export const RESPONSE_PARTECIPATION_START   = 'RESPONSE_PARTECIPATION_START'
export const RESPONSE_PARTECIPATION_SUCCESS = 'RESPONSE_PARTECIPATION_SUCCESS'
export const RESPONSE_PARTECIPATION_FAILED  = 'RESPONSE_PARTECIPATION_FAILED'

export const REMOVE_PARTECIPATION_START   = 'REMOVE_PARTECIPATION_START'
export const REMOVE_PARTECIPATION_SUCCESS = 'REMOVE_PARTECIPATION_SUCCESS'
export const REMOVE_PARTECIPATION_FAILED  = 'REMOVE_PARTECIPATION_FAILED'

export const FETCH_NOTIFICATIONS_START   = 'FETCH_NOTIFICATIONS_START'
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS'
export const FETCH_NOTIFICATIONS_FAILED  = 'FETCH_NOTIFICATIONS_FAILED'

export const SET_NOTIFICATION_READ = 'SET_NOTIFICATION_READ'