export const SIGNUP_START   = 'SIGNUP_START'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILED  = 'SIGNUP_FAILED'

export const LOGIN_START    = 'LOGIN_START'
export const LOGIN_SUCCESS  = 'LOGIN_SUCCESS'
export const LOGIN_FAILED   = 'LOGIN_FAILED'

export const LOGOUT_START   = 'LOGOUT_START'
export const LOGOUT_SUCCESS	= 'LOGOUT_SUCCESS'

export const REAUTHENTICATE_START   = 'REAUTHENTICATE_START'
export const REAUTHENTICATE_SUCCESS = 'REAUTHENTICATE_SUCCESS'
export const REAUTHENTICATE_FAILED  = 'REAUTHENTICATE_FAILED'

export const UPDATE_PROFILE_START   = 'UPDATE_PROFILE_START'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED  = 'UPDATE_PROFILE_FAILED'